### ISSUE TITLE
Add JSON file for the list of tasks

### ISSUE THREAD

**Issue by RamtinTJB** [cse110-sp24-group12/warmup-exercise#3]
add a file named `tasks.json` in the task list folder which includes a static list of the task that will be shown in the widget. Here is an example of a task in JSON:

```json
[
  {
    "title": "Clean the garage",
    "is_done": false,
    "due_date": "2024-04-23T18:25:43.511Z"
  }
]
```

**Comment by lindseyrapp** [comment]
Looks great!
